name: Build

on:
  workflow_call:
    inputs:
      imageTag:
        required: true
        type: string

jobs:
  build_service_binary:
    name: Build service binary
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.17
          check-latest: true

      - name: Build binary
        run: echo "Build binary"

  build_flyway_docker_image:
    name: Build flyway docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: echo "Build and push docker image"

  build_service_docker_image:
    name: Build service docker image
    runs-on: ubuntu-latest
    needs: [build_service_binary]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        run: echo "Download artifact"

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: echo "Build and push docker image"

  build_documentation_docker_image:
    name: Build documentation docker image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup docker buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        run: echo "Build and push docker image"
